---
title: "Project 2"
author: "Group 5: Siyu Li, Yawen Zhou, Tien Nguyen, Sally Zhao" 
output: html_document
---
###Data cleaning (please delete this message before submitting)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, warning=FALSE, message=FALSE}
library(readr)
library(dplyr)
```

```{r read data, warning=FALSE, message=FALSE, echo=FALSE}
data <- read_csv('./DisasterDeclarationsSummaries.csv')
selected_columns <- c('id', 'declarationTitle', 'incidentType', 'state', 'declarationType', 'declarationDate', 'incidentBeginDate', 'incidentEndDate')
selected_data <- select(data, all_of(selected_columns))
```

```{r columns of date, message=FALSE, echo=FALSE}
selected_data$declarationDate <- as.Date(selected_data$declarationDate)
selected_data$incidentBeginDate <- as.Date(selected_data$incidentBeginDate)
selected_data$incidentEndDate <- as.Date(selected_data$incidentEndDate)
```

```{r}
fire_data <- filter(selected_data, incidentType == 'Fire')
```

```{r export data, message=FALSE,echo=FALSE}
write_csv(fire_data, "../output/processed_moments.csv")
```




